In [2]:
import numpy as np

In [6]:
a = np.array([100,40])
print(a)

[100  40]


In [4]:
type(a)

numpy.ndarray

In [7]:
a.shape

(2,)

In [11]:
data = np.array([[3,104],
                 [2,100],
                 [1,81],
                 [99,5],
                 [98,2]])
print(data)
print(data.shape)

[[  3 104]
 [  2 100]
 [  1  81]
 [ 99   5]
 [ 98   2]]
(5, 2)


In [12]:
dianying = np.array([[18,90]])
print(dianying)

[[18 90]]


In [13]:
distance = data - dianying
print(distance)

[[-15  14]
 [-16  10]
 [-17  -9]
 [ 81 -85]
 [ 80 -88]]


In [14]:
square = np.power(distance,2)
print(square)

[[ 225  196]
 [ 256  100]
 [ 289   81]
 [6561 7225]
 [6400 7744]]


In [18]:
sum_= np.sum(square,axis=1)
print(sum_)

[  421   356   370 13786 14144]


In [19]:
sqrt = np.sqrt(sum_)
print(sqrt)

[ 20.51828453  18.86796226  19.23538406 117.41379817 118.92854998]


In [33]:
sort_ = np.sort(sqrt)
print(sort_)

[ 18.86796226  19.23538406  20.51828453 117.41379817 118.92854998]


In [26]:
sort_[0:3]

array([18.86796226, 19.23538406, 20.51828453])

In [29]:
def Joker(name):
    print('hello',name)
    return 'OK'

In [30]:
Joker('Good')

hello Good


'OK'

In [38]:
def KNN(test_samples,K): 
    #1.Loading train data set.
    data = np.array([[3,104],
            [2,100],
            [1,81],
            [101.10],
            [99,5],
            [98,2]])
    #2.distance
    dianying = np.array([[18,90]])
    distance = data - dianying
    square = np.power(distance,2)
    sum_= np.sum(square,axis=1)
    sqrt = np.sqrt(sum_)
    #3.sort.
    sort_ = np.sort(sqrt)
    #4.K
    sort_[0,test_samples]
    #return classes.
    return 'test_samples'

In [39]:
KNN(3)

TypeError: KNN() missing 1 required positional argument: 'K'